---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stasik.
--- DateTime: 27.02.2020 17:30
---
do




    function OnUnitCreated(unit)
        local id = GetUnitTypeId(unit)

            if id == FourCC("e001") then
                CreateSpiceTexttag(unit, false)
            elseif id == FourCC("h000") then
                CreateSpiceTexttag(unit, true)
                CreateRefineryProximity(unit)
            end



    end


end