---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stasik.
--- DateTime: 26.02.2020 3:11
---
do


    local TEXT_SIZE = (8.2 * 0.023) / 10.
    local TEXXTAG_STATE = {
        "|c0000FF00=|r======",
        "|c0000FF00==|r=====",
        "|c0000FF00===|r====",
        "|c0000FF00====|r===",
        "|c0000FF00=====|r==",
        "|c0000FF00======|r=",
        "|c0000FF00=======|r",
    }




    function GetNearestSpice(unit)
        local range = 50.
        local x = GetUnitX(unit)
        local y = GetUnitY(unit)
        local rect = Rect(x - range, y - range, x + range, y + range)
        local spice

            while not spice do
                EnumDestructablesInRect(rect, nil, function() if GetDestructableTypeId(GetEnumDestructable()) == FourCC("B000") then spice = GetEnumDestructable() end end)
                range = range + 100.
                SetRect(rect, x - range, y - range, x + range, y + range)
                if range > 5000. then return end
            end

            RemoveRect(rect)

        return spice
    end








    function UpdateSpiceText(target)
        local unit_data = GetUnitData(target)
        local spice_value = math.floor(unit_data.spice_value / 100.)

            SetTextTagText(unit_data.spice_text, TEXXTAG_STATE[spice_value] or "=======", TEXT_SIZE)
    end


    function CreateSpiceTexttag(target)
        local unit_data = GetUnitData(target)
        local text = CreateTextTag()

            SetTextTagPosUnit(text, target, 5.)
            SetTextTagText(text, "=======", TEXT_SIZE)
            SetTextTagVisibility(text, GetLocalPlayer() == GetOwningPlayer(target))
            unit_data.spice_text = text
            unit_data.spice_value = 0.
    end


    function HarvestInit()
        local Trigger = CreateTrigger()
        TriggerRegisterAnyUnitEventBJ(Trigger, EVENT_PLAYER_UNIT_SPELL_EFFECT)
        TriggerAddAction(Trigger, function()

            if GetSpellAbilityId() == FourCC("A01J") then
                local unit_data = GetUnitData(GetTriggerUnit())
                local spice = GetSpellTargetDestructable()
                local new_life = GetWidgetLife(spice) - 100.

                SetDestructableLife(spice, new_life)
                unit_data.spice_value = unit_data.spice_value + 100.
                UpdateSpiceText(unit_data.owner)
                print("casted")

                if not (new_life > 0.) then
                    spice = GetNearestSpice(unit_data.owner)
                    if spice then IssueTargetDestructableOrder(unit_data.owner, order_hex, spice) end
                    print("new spice seek")
                elseif unit_data.spice_value > 700. then
                    unit_data.spice_value = 700.
                    IssueImmediateOrderById(unit_data.owner, order_stop)
                    print("full")
                else
                    IssueTargetDestructableOrder(unit_data.owner, order_hex, spice)
                    print("reorder")
                end

            end

        end)


        Trigger = CreateTrigger()
        TriggerRegisterAnyUnitEventBJ(Trigger, EVENT_PLAYER_UNIT_SPELL_EFFECT)
        TriggerAddAction(Trigger, function()

            if GetSpellAbilityId() == FourCC("A01I") then
                local unit_data = GetUnitData(GetTriggerUnit())
                local spice = GetNearestSpice(unit_data.owner)

                if spice then IssueTargetDestructableOrder(unit_data.owner, order_hex, spice) end
                print("get target spice")

            end
            print("AAAAAAAA")
        end)
    end



end