---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stasik.
--- DateTime: 25.02.2020 19:04
---

do



    function GetMissileData(id)
        return MissileList[FourCC(id)] or nil
    end


    function NewMissileTemplate(id, missile_reference)
        local new_missile = {

            name = "",
            id = id,
            model = "",
            decay = 0,

            effect_on_target_scale = 1.,
            effect_on_target_point = "",
            effect_on_target = "",
            effect_on_loc = "",

            sound_on_hit = {},
            sound_on_launch = {},
            sound_on_destroy = {},
            sound_on_fly = nil,

            effect_on_impact = nil,
            effect_on_hit = nil,
            effect_on_expire = nil,
            effect_get_level_from_skill = nil,

            radius = 0.,
            max_distance = 0.,
            speed = 0.,
            scale = 1.,

            lightning_id = nil,
            lightning_length = 0.,

            max_targets = 1,
            hit_once_in = 0.,

            start_z = 0.,
            end_z = 0.,
            arc = 0.,

            revert = false,
            trackable = false,

            full_distance = false,
            only_on_target = false,
            only_on_impact = false,
            penetrate = false,
            ignore_terrain = false

        }

        --real MissileOffset


        MergeTables(new_missile, missile_reference)

        if new_missile.full_distance == nil then
            new_missile.full_distance = false
        end

        if new_missile.only_on_target == nil then
            new_missile.only_on_target = false
        end

        if new_missile.only_on_impact == nil then
            new_missile.only_on_impact = false
        end

        if new_missile.ignore_terrain == nil then
            new_missile.ignore_terrain = false
        end

        if new_missile.penetrate == nil then
            new_missile.penetrate = false
        end

        if new_missile.scale == nil then
            new_missile.scale = 1.
        end

        if new_missile.max_targets == nil then
            new_missile.max_targets = 1
        end

        MissileList[FourCC(id)] = new_missile
    end


    function DefineMissilesData()
        MissileList = {}
        NewMissileTemplate('M001', {
            name = "test missile",
            model = ".mdx",
            max_distance = 1000.,
            radius = 50.,
            speed = 400.,
            start_z = 65.,
            lightning_id = 'CHIM',
            lightning_length = 125.,
            end_z = 65.,
            arc = 0.,
            ignore_terrain = true,
            full_distance = true,
            penetrate = false,
            trackable = false,
            only_on_impact = true
        })
        --============================================
        NewMissileTemplate('M002', {
            name = "tank shell",
            model = ".mdx",
            max_distance = 800.,
            radius = 50.,
            speed = 1200.,
            start_z = 55.,
            end_z = 55.,
            arc = 0.,
            ignore_terrain = true,
            full_distance = false,
            penetrate = false,
            trackable = false,
            only_on_impact = true
        })
        --============================================
        NewMissileTemplate('M003', {
            name = "quad missile",
            model = ".mdx",
            max_distance = 600.,
            radius = 50.,
            speed = 1000.,
            start_z = 55.,
            end_z = 55.,
            arc = 0.,
            ignore_terrain = true,
            full_distance = false,
            penetrate = false,
            trackable = false,
            only_on_impact = true
        })
        --============================================
        NewMissileTemplate('M006', {
            name = "trooper missile",
            model = ".mdx",
            max_distance = 600.,
            radius = 50.,
            speed = 1000.,
            start_z = 45.,
            end_z = 45.,
            arc = 0.,
            ignore_terrain = true,
            full_distance = false,
            penetrate = false,
            trackable = false,
            only_on_impact = true
        })
        --============================================
        NewMissileTemplate('M004', {
            name = "launcher missile",
            model = ".mdx",
            max_distance = 1000.,
            radius = 50.,
            speed = 1000.,
            start_z = 65.,
            end_z = 65.,
            arc = 0.25,
            sound_on_destroy = {
                pack = { "Sound\\EXPLSML1.wav", "Sound\\EXPLSML2.wav", "Sound\\EXPLSML3.wav", "Sound\\EXPLSML4.wav" },
                volume = 45,
                cutoff = 1600.,
            },
            ignore_terrain = true,
            full_distance = false,
            penetrate = false,
            trackable = false,
            only_on_impact = true
        })
        --============================================
        NewMissileTemplate('M005', {
            name = "siege shell",
            model = ".mdx",
            max_distance = 1000.,
            radius = 50.,
            speed = 700.,
            start_z = 70.,
            end_z = 65.,
            arc = 0.4,
            sound_on_destroy = {
                pack = { "Sound\\NAPALM1.wav" },
                volume = 55,
                cutoff = 1600.,
            },
            ignore_terrain = true,
            full_distance = false,
            penetrate = false,
            trackable = false,
            only_on_impact = true
        })
    end

end
