---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stasik.
--- DateTime: 25.02.2020 19:04
---
do




    function GetWeaponData(id)
        return WeaponList[FourCC(id)] or nil
    end


    function NewWeaponTemplate(reference)
        MissileList[FourCC(reference.id)] = MergeTables({}, reference)
    end


    function DefineWeaponsData()
        WeaponList = {}
        DefineMissilesData()
        --=======================================================
        NewWeaponTemplate({
            id = "inft",
            sound = "Sound\\MGUN2.wav",
        })
        --=======================================================
        NewWeaponTemplate({
            id = "trke",
            sound = "Sound\\20MMGUN1.wav",
        })
        --=======================================================
        NewWeaponTemplate({
            id = "tank",
            sound = "Sound\\MEDTANK1.wav",
            missile = GetMissileData("M002")
        })
        --=======================================================
        NewWeaponTemplate({
            id = "quad",
            sound = "Sound\\ROCKET1.wav",
            missile = GetMissileData("M003")
        })
        --=======================================================
        NewWeaponTemplate({
            id = "trpr",
            sound = "Sound\\BAZOOK1.wav",
            missile = GetMissileData("M006")
        })
        --=======================================================
        NewWeaponTemplate({
            id = "lnch",
            sound = "Sound\\MISSLE1.wav",
            missile = GetMissileData("M004")
        })
        --=======================================================
        NewWeaponTemplate({
            id = "sieg",
            sound = "Sound\\MORTAR1.wav",
            missile = GetMissileData("M005")
        })
        --=======================================================
    end


end